#ifndef BOLR_STATUS_H
#define BOLR_STATUS_H

#include "bolr/types.h"

enum {
    BOLR_OK = 0,
    BOLR_INVALID_ARGUMENT = 1,
    BOLR_INVALID_SHAPE = 2,
    BOLR_NONFINITE_INPUT = 3,
    BOLR_ALLOCATION_FAILED = 4,
    BOLR_DIMENSION_OVERFLOW = 5,
    BOLR_NOT_POSITIVE_DEFINITE = 6,
    BOLR_SINGULAR_MATRIX = 7,
    BOLR_NUMERICAL_FAILURE = 8,
    BOLR_SCHEMA_MISMATCH = 9,
    BOLR_VERSION_MISMATCH = 10,
    BOLR_INCOMPATIBLE_CHECKPOINT = 11,
    BOLR_UNSUPPORTED_OPERATION = 12,
    BOLR_ALREADY_CLOSED = 13
};

const char *bolr_status_string(bolr_status status);

#endif
