#ifndef BOLR_TEST_SUITE_H
#define BOLR_TEST_SUITE_H

int test_math(void);
int test_linalg(void);
int test_ownership(void);
int test_state_layout(void);
int test_score(void);
int test_candidate_a(void);
int test_candidate_a_target(void);
int test_ordered_partition(void);
int test_candidate_b_exact(void);
int test_candidate_b_sampled(void);
int test_candidate_b_laplace(void);
int test_standardizer(void);
int test_bocpd(void);
int test_attribution(void);
int test_partial_reset(void);
int test_adaptive_policy(void);
int test_adaptive_checkpoint(void);
int test_score_uncertainty(void);
int test_pairwise_probability(void);
int test_decision_policy(void);
int test_consensus_region(void);
int test_connected_components(void);
int test_region_summary(void);
int test_graph_medoid(void);
int test_decision_calibration(void);
int test_penalty(void);
int test_dynamics(void);
int test_golden(void);
int test_gaussian_state(void);
int test_gaussian_prediction(void);
int test_rng(void);
int test_sampling(void);
int test_rank_accumulator(void);
int test_replay(void);
int test_checkpoint_header(void);
int test_checkpoint_sections(void);
int test_checkpoint_codec(void);
int test_checkpoint_corruption(void);
int test_checkpoint_file(void);
int test_checkpoint_restart(void);
int test_posterior_objective(void);
int test_newton(void);
int test_laplace(void);
int test_static_fit(void);
int test_inference_ownership(void);

#endif
